---
editor_options:
  markdown:
    wrap: 72
---

# Fitting CFA Models: A Case Study using the SF-36 "Mental Health" scale {.unnumbered}

Use the `lavaan` tutorial https://www.lavaan.ugent.be/tutorial/cfa.html to help you carry out the tasks below. 

You will also require `tidyverse` and `psych`. Please make sure to install the `psych` package if you have not done so before. 

## Task and Questions {-}

Fit a CFA model assuming a single latent factor that is indicated by items "nervous", "down", "peace", "sad", "happy" and include intercepts (`meanstructure`) in the model. Then answer the questions below. 

:::question
1. Interpret the factor loadings: what do these tell us? Interpret both the unstandardised and standardised loadings. Remember, you ask for the standardised results by adding `standardized = TRUE` in the `summary()` function.  

2. Interpret the item intercepts: What do these tell us?  

3. Interpret the residuals: What do these tell us? Tip: See https://lavaan.ugent.be/tutorial/inspect.html  

4. Interpret the model fit indices (CFI, SRMR, RMSEA): what do these tell us? Tip: You ask for the fit indices by adding `fit.measures = TRUE` in the `summary()` function.  

5. Overall, do you support the claim made by [Ware 2000](https://journals.lww.com/spinejournal/citation/2000/12150/sf_36_health_survey_update.8.aspx) that these five items plausibly reflect a single, latent factor?   
:::