<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>An Introduction to lavaan: How Do Wet Fingers Wrinkle? | SOST70073 Structural Equation Modelling</title>
  <meta name="description" content="Notebook hosting practical materials for SOST70033." />
  <meta name="generator" content="bookdown 0.38 and GitBook 2.6.7" />

  <meta property="og:title" content="An Introduction to lavaan: How Do Wet Fingers Wrinkle? | SOST70073 Structural Equation Modelling" />
  <meta property="og:type" content="book" />
  
  <meta property="og:description" content="Notebook hosting practical materials for SOST70033." />
  

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="An Introduction to lavaan: How Do Wet Fingers Wrinkle? | SOST70073 Structural Equation Modelling" />
  
  <meta name="twitter:description" content="Notebook hosting practical materials for SOST70033." />
  

<meta name="author" content="Dr. Nick Shryane" />



  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="an-introduction-to-lavaan-how-do-wet-fingers-wrinkle.html"/>

<script src="libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/fuse.js@6.4.6/dist/fuse.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />








<link href="libs/anchor-sections-1.1.0/anchor-sections.css" rel="stylesheet" />
<link href="libs/anchor-sections-1.1.0/anchor-sections-hash.css" rel="stylesheet" />
<script src="libs/anchor-sections-1.1.0/anchor-sections.js"></script>


<style type="text/css">
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { color: #008000; } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { color: #008000; font-weight: bold; } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>

<style type="text/css">
  
  div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
</style>

<link rel="stylesheet" href="style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li class="toc-logo"><a href="./"><img src="images/logos/uom_logo.png"></a></li>

<li class="divider"></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i>About</a></li>
<li class="part"><span><b>Section 1</b></span></li>
<li class="chapter" data-level="" data-path="overview.html"><a href="overview.html"><i class="fa fa-check"></i>Overview</a></li>
<li class="chapter" data-level="" data-path="an-introduction-to-lavaan-how-do-wet-fingers-wrinkle.html"><a href="an-introduction-to-lavaan-how-do-wet-fingers-wrinkle.html"><i class="fa fa-check"></i>An Introduction to <code>lavaan</code>: How Do Wet Fingers Wrinkle?</a>
<ul>
<li class="chapter" data-level="" data-path="an-introduction-to-lavaan-how-do-wet-fingers-wrinkle.html"><a href="an-introduction-to-lavaan-how-do-wet-fingers-wrinkle.html#workspace"><i class="fa fa-check"></i>Workspace</a></li>
<li class="chapter" data-level="" data-path="an-introduction-to-lavaan-how-do-wet-fingers-wrinkle.html"><a href="an-introduction-to-lavaan-how-do-wet-fingers-wrinkle.html#data"><i class="fa fa-check"></i>Data</a></li>
<li class="chapter" data-level="" data-path="an-introduction-to-lavaan-how-do-wet-fingers-wrinkle.html"><a href="an-introduction-to-lavaan-how-do-wet-fingers-wrinkle.html#experimental-design"><i class="fa fa-check"></i>Experimental Design</a></li>
<li class="chapter" data-level="" data-path="an-introduction-to-lavaan-how-do-wet-fingers-wrinkle.html"><a href="an-introduction-to-lavaan-how-do-wet-fingers-wrinkle.html#frequency-for-variables-and-levels"><i class="fa fa-check"></i>Frequency for Variables and Levels</a></li>
<li class="chapter" data-level="" data-path="an-introduction-to-lavaan-how-do-wet-fingers-wrinkle.html"><a href="an-introduction-to-lavaan-how-do-wet-fingers-wrinkle.html#the-causal-model"><i class="fa fa-check"></i>The Causal Model</a></li>
<li class="chapter" data-level="" data-path="an-introduction-to-lavaan-how-do-wet-fingers-wrinkle.html"><a href="an-introduction-to-lavaan-how-do-wet-fingers-wrinkle.html#statistical-model"><i class="fa fa-check"></i>Statistical Model</a></li>
<li class="chapter" data-level="" data-path="an-introduction-to-lavaan-how-do-wet-fingers-wrinkle.html"><a href="an-introduction-to-lavaan-how-do-wet-fingers-wrinkle.html#preparing-the-data"><i class="fa fa-check"></i>Preparing the Data</a></li>
<li class="chapter" data-level="" data-path="an-introduction-to-lavaan-how-do-wet-fingers-wrinkle.html"><a href="an-introduction-to-lavaan-how-do-wet-fingers-wrinkle.html#visualing-the-data"><i class="fa fa-check"></i>Visualing the Data</a></li>
<li class="chapter" data-level="" data-path="an-introduction-to-lavaan-how-do-wet-fingers-wrinkle.html"><a href="an-introduction-to-lavaan-how-do-wet-fingers-wrinkle.html#the-lavaan-package"><i class="fa fa-check"></i>The <code>lavaan</code> Package</a></li>
<li class="chapter" data-level="" data-path="an-introduction-to-lavaan-how-do-wet-fingers-wrinkle.html"><a href="an-introduction-to-lavaan-how-do-wet-fingers-wrinkle.html#task-1"><i class="fa fa-check"></i>TASK 1</a></li>
<li class="chapter" data-level="" data-path="an-introduction-to-lavaan-how-do-wet-fingers-wrinkle.html"><a href="an-introduction-to-lavaan-how-do-wet-fingers-wrinkle.html#the-lavaan-package-1"><i class="fa fa-check"></i>The <code>lavaan</code> Package</a></li>
<li class="chapter" data-level="" data-path="an-introduction-to-lavaan-how-do-wet-fingers-wrinkle.html"><a href="an-introduction-to-lavaan-how-do-wet-fingers-wrinkle.html#task-2"><i class="fa fa-check"></i>TASK 2</a></li>
<li class="chapter" data-level="" data-path="an-introduction-to-lavaan-how-do-wet-fingers-wrinkle.html"><a href="an-introduction-to-lavaan-how-do-wet-fingers-wrinkle.html#task-3"><i class="fa fa-check"></i>Task 3</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="an-introduction-to-lavaan-how-do-wet-fingers-wrinkle-1.html"><a href="an-introduction-to-lavaan-how-do-wet-fingers-wrinkle-1.html"><i class="fa fa-check"></i>An Introduction to <code>lavaan</code>: How Do Wet Fingers Wrinkle?</a>
<ul>
<li class="chapter" data-level="" data-path="an-introduction-to-lavaan-how-do-wet-fingers-wrinkle-1.html"><a href="an-introduction-to-lavaan-how-do-wet-fingers-wrinkle-1.html#workspace-1"><i class="fa fa-check"></i>Workspace</a></li>
<li class="chapter" data-level="" data-path="an-introduction-to-lavaan-how-do-wet-fingers-wrinkle-1.html"><a href="an-introduction-to-lavaan-how-do-wet-fingers-wrinkle-1.html#data-1"><i class="fa fa-check"></i>Data</a></li>
<li class="chapter" data-level="" data-path="an-introduction-to-lavaan-how-do-wet-fingers-wrinkle-1.html"><a href="an-introduction-to-lavaan-how-do-wet-fingers-wrinkle-1.html#experimental-design-1"><i class="fa fa-check"></i>Experimental Design</a></li>
<li class="chapter" data-level="" data-path="an-introduction-to-lavaan-how-do-wet-fingers-wrinkle-1.html"><a href="an-introduction-to-lavaan-how-do-wet-fingers-wrinkle-1.html#frequency-for-variables-and-levels-1"><i class="fa fa-check"></i>Frequency for Variables and Levels</a></li>
<li class="chapter" data-level="" data-path="an-introduction-to-lavaan-how-do-wet-fingers-wrinkle-1.html"><a href="an-introduction-to-lavaan-how-do-wet-fingers-wrinkle-1.html#the-causal-model-1"><i class="fa fa-check"></i>The Causal Model</a></li>
<li class="chapter" data-level="" data-path="an-introduction-to-lavaan-how-do-wet-fingers-wrinkle-1.html"><a href="an-introduction-to-lavaan-how-do-wet-fingers-wrinkle-1.html#statistical-model-1"><i class="fa fa-check"></i>Statistical Model</a></li>
<li class="chapter" data-level="" data-path="an-introduction-to-lavaan-how-do-wet-fingers-wrinkle-1.html"><a href="an-introduction-to-lavaan-how-do-wet-fingers-wrinkle-1.html#preparing-the-data-1"><i class="fa fa-check"></i>Preparing the Data</a></li>
<li class="chapter" data-level="" data-path="an-introduction-to-lavaan-how-do-wet-fingers-wrinkle-1.html"><a href="an-introduction-to-lavaan-how-do-wet-fingers-wrinkle-1.html#visualing-the-data-1"><i class="fa fa-check"></i>Visualing the Data</a></li>
<li class="chapter" data-level="" data-path="an-introduction-to-lavaan-how-do-wet-fingers-wrinkle-1.html"><a href="an-introduction-to-lavaan-how-do-wet-fingers-wrinkle-1.html#the-lavaan-package-2"><i class="fa fa-check"></i>The <code>lavaan</code> Package</a></li>
<li class="chapter" data-level="" data-path="an-introduction-to-lavaan-how-do-wet-fingers-wrinkle-1.html"><a href="an-introduction-to-lavaan-how-do-wet-fingers-wrinkle-1.html#task-1-1"><i class="fa fa-check"></i>TASK 1</a></li>
<li class="chapter" data-level="" data-path="an-introduction-to-lavaan-how-do-wet-fingers-wrinkle-1.html"><a href="an-introduction-to-lavaan-how-do-wet-fingers-wrinkle-1.html#task-2-1"><i class="fa fa-check"></i>TASK 2</a></li>
<li class="chapter" data-level="" data-path="an-introduction-to-lavaan-how-do-wet-fingers-wrinkle-1.html"><a href="an-introduction-to-lavaan-how-do-wet-fingers-wrinkle-1.html#task-3-1"><i class="fa fa-check"></i>Task 3</a></li>
</ul></li>
<li class="divider"></li>
<li><a href="https://github.com/rstudio/bookdown" target="blank">Published with bookdown</a></li>
</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">SOST70073 Structural Equation Modelling</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<hr>
<center> 
  <div class="header">
   <img src="images/banners/SEM_banner.png" alt="Trulli">
  </div>
</center>
<div id="an-introduction-to-lavaan-how-do-wet-fingers-wrinkle-1" class="section level1 unnumbered hasAnchor">
<h1>An Introduction to <code>lavaan</code>: How Do Wet Fingers Wrinkle?<a href="an-introduction-to-lavaan-how-do-wet-fingers-wrinkle-1.html#an-introduction-to-lavaan-how-do-wet-fingers-wrinkle-1" class="anchor-section" aria-label="Anchor link to header"></a></h1>
<p>We’re going to run some linear regression models using the familar
<code>lm()</code> library. Then we’re going to run them using functions from the
<code>lavaan</code> library. They will be the same models, with (almost) the same
results. The aim is to show you that the basic building block of a SEM
is just a regression model.</p>
<p>For this demonstration, we will make use of data from the following
study:</p>
<p>Kareklas, et al. (2013) “Water-induced finger wrinkles improve handling
of wet objects”, Biology Letters,
<a href="http://dx.doi.org/10.1098/rsbl.2012.0999" class="uri">http://dx.doi.org/10.1098/rsbl.2012.0999</a></p>
<div id="workspace-1" class="section level2 unnumbered hasAnchor">
<h2>Workspace<a href="an-introduction-to-lavaan-how-do-wet-fingers-wrinkle-1.html#workspace-1" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>First, we’re going to clear the workspace (beware! This will remove
everything from the “environment”).</p>
<div class="sourceCode" id="cb30"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb30-1"><a href="an-introduction-to-lavaan-how-do-wet-fingers-wrinkle-1.html#cb30-1" tabindex="-1"></a><span class="fu">rm</span>(<span class="at">list =</span> <span class="fu">ls</span>())</span></code></pre></div>
<p>Now, let’s set the working directory. You will remember that the working
directory is the folder where R will look for and save files to. If you
want to know what your current working directory is, run the command
below:</p>
<div class="sourceCode" id="cb31"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb31-1"><a href="an-introduction-to-lavaan-how-do-wet-fingers-wrinkle-1.html#cb31-1" tabindex="-1"></a><span class="fu">getwd</span>() </span></code></pre></div>
<p>To change it, modify the path in the quotation marks <code>" "</code> below to your
directory.</p>
<div class="sourceCode" id="cb32"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb32-1"><a href="an-introduction-to-lavaan-how-do-wet-fingers-wrinkle-1.html#cb32-1" tabindex="-1"></a><span class="fu">setwd</span>(<span class="st">&quot;C:/Users/...&quot;</span>)</span></code></pre></div>
<p>Now let’s load the relevant packages. In this demonstration, we’ll be
using the <code>lavaan</code> library, but also a few others: <code>fastDummies</code> which
will facilitate the generation of dummy variables, and <code>emeans</code> for
computing and plotting estimated marginal means. You must install these
prior to loading them.</p>
<div class="sourceCode" id="cb33"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb33-1"><a href="an-introduction-to-lavaan-how-do-wet-fingers-wrinkle-1.html#cb33-1" tabindex="-1"></a><span class="fu">install.packages</span>(<span class="st">&quot;lavaan&quot;</span>)</span>
<span id="cb33-2"><a href="an-introduction-to-lavaan-how-do-wet-fingers-wrinkle-1.html#cb33-2" tabindex="-1"></a><span class="fu">install.packages</span>(<span class="st">&quot;fastDummies&quot;</span>)</span>
<span id="cb33-3"><a href="an-introduction-to-lavaan-how-do-wet-fingers-wrinkle-1.html#cb33-3" tabindex="-1"></a><span class="fu">install.packages</span>(<span class="st">&quot;emmeans&quot;</span>)</span></code></pre></div>
<p>In addition to these, we will also need <code>tidyverse</code> to allow us to make
use of the pipe operator, <code>ggplot2</code> for plotting results and <code>janitor</code>
for generating frequency tables.</p>
<div class="sourceCode" id="cb34"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb34-1"><a href="an-introduction-to-lavaan-how-do-wet-fingers-wrinkle-1.html#cb34-1" tabindex="-1"></a><span class="fu">library</span>(<span class="st">&quot;lavaan&quot;</span>)</span>
<span id="cb34-2"><a href="an-introduction-to-lavaan-how-do-wet-fingers-wrinkle-1.html#cb34-2" tabindex="-1"></a><span class="fu">library</span>(<span class="st">&quot;tidyverse&quot;</span>)           </span>
<span id="cb34-3"><a href="an-introduction-to-lavaan-how-do-wet-fingers-wrinkle-1.html#cb34-3" tabindex="-1"></a><span class="fu">library</span>(<span class="st">&quot;janitor&quot;</span>)             </span>
<span id="cb34-4"><a href="an-introduction-to-lavaan-how-do-wet-fingers-wrinkle-1.html#cb34-4" tabindex="-1"></a><span class="fu">library</span>(<span class="st">&quot;fastDummies&quot;</span>)        </span>
<span id="cb34-5"><a href="an-introduction-to-lavaan-how-do-wet-fingers-wrinkle-1.html#cb34-5" tabindex="-1"></a><span class="fu">library</span>(<span class="st">&quot;ggplot2&quot;</span>)             </span>
<span id="cb34-6"><a href="an-introduction-to-lavaan-how-do-wet-fingers-wrinkle-1.html#cb34-6" tabindex="-1"></a><span class="fu">library</span>(<span class="st">&quot;emmeans&quot;</span>)             </span></code></pre></div>
</div>
<div id="data-1" class="section level2 unnumbered hasAnchor">
<h2>Data<a href="an-introduction-to-lavaan-how-do-wet-fingers-wrinkle-1.html#data-1" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>We’ll download the data from the internet, and store it in a dataframe
called <strong>wrinkle</strong>.</p>
<div class="sourceCode" id="cb35"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb35-1"><a href="an-introduction-to-lavaan-how-do-wet-fingers-wrinkle-1.html#cb35-1" tabindex="-1"></a>wrinkle <span class="ot">&lt;-</span> <span class="fu">read.csv</span>(<span class="st">&quot;https://vincentarelbundock.github.io/Rdatasets/csv/Stat2Data/Wrinkle.csv&quot;</span>)</span></code></pre></div>
</div>
<div id="experimental-design-1" class="section level2 unnumbered hasAnchor">
<h2>Experimental Design<a href="an-introduction-to-lavaan-how-do-wet-fingers-wrinkle-1.html#experimental-design-1" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>The skin on our fingers and toes wrinkles when it has been in water for
a few minutes. Why on earth does it do this? The skin on almost all
other body parts does not wrinkle when wet.</p>
<p>Twenty participants were asked to pick up small objects with the right
hand thumb and index finger, pass them through a small hole, grab them
with the left hand, and put them into a box that had a hole in the lid.
For half the trials, participants had their fingers soaked in water,
making the skin wrinkle. On the other half of the trials, the fingers
were dry. For half the trials the objects were wet. For the other half,
the objects were dry.</p>
<p>The time it took the participants to finish the task of passing all of
the objects into the box was recorded for each condition:</p>
<ul>
<li>Condition 1: Wet/wrinkled fingers, wet objects<br />
</li>
<li>Condition 2: Wet/wrinkled fingers, dry objects<br />
</li>
<li>Condition 3: Dry fingers, wet objects<br />
</li>
<li>Condition 4: Dry fingers, dry objects</li>
</ul>
<p><em>Hypothesis</em>: Skin wrinkling is an adaptation to improve grip when in
wet environments. That’s why we only need it on our fingers (for
handling wet objects) and toes (for walking on wet surfaces).</p>
<p><em>Research Question</em>: Will objects be easier/quicker to handle with
wrinkled/wet fingers compared to with dry fingers?</p>
</div>
<div id="frequency-for-variables-and-levels-1" class="section level2 unnumbered hasAnchor">
<h2>Frequency for Variables and Levels<a href="an-introduction-to-lavaan-how-do-wet-fingers-wrinkle-1.html#frequency-for-variables-and-levels-1" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>Fingers were wet/wrinkled half the time</p>
<div class="sourceCode" id="cb36"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb36-1"><a href="an-introduction-to-lavaan-how-do-wet-fingers-wrinkle-1.html#cb36-1" tabindex="-1"></a>wrinkle <span class="sc">%&gt;%</span> <span class="fu">tabyl</span>(Fingers) </span></code></pre></div>
<pre><code>##   Fingers  n percent
##       non 40     0.5
##  wrinkled 40     0.5</code></pre>
<p>Objects were wet half the time</p>
<div class="sourceCode" id="cb38"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb38-1"><a href="an-introduction-to-lavaan-how-do-wet-fingers-wrinkle-1.html#cb38-1" tabindex="-1"></a>wrinkle <span class="sc">%&gt;%</span> <span class="fu">tabyl</span>(Objects)</span></code></pre></div>
<pre><code>##  Objects  n percent
##      dry 40     0.5
##      wet 40     0.5</code></pre>
<p>Participants 1 to 20 (all four conditions)</p>
<div class="sourceCode" id="cb40"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb40-1"><a href="an-introduction-to-lavaan-how-do-wet-fingers-wrinkle-1.html#cb40-1" tabindex="-1"></a>wrinkle <span class="sc">%&gt;%</span> <span class="fu">tabyl</span>(Participant) </span></code></pre></div>
<pre><code>##  Participant n percent
##           p1 4    0.05
##          p10 4    0.05
##          p11 4    0.05
##          p12 4    0.05
##          p13 4    0.05
##          p14 4    0.05
##          p15 4    0.05
##          p16 4    0.05
##          p17 4    0.05
##          p18 4    0.05
##          p19 4    0.05
##           p2 4    0.05
##          p20 4    0.05
##           p3 4    0.05
##           p4 4    0.05
##           p5 4    0.05
##           p6 4    0.05
##           p7 4    0.05
##           p8 4    0.05
##           p9 4    0.05</code></pre>
</div>
<div id="the-causal-model-1" class="section level2 unnumbered hasAnchor">
<h2>The Causal Model<a href="an-introduction-to-lavaan-how-do-wet-fingers-wrinkle-1.html#the-causal-model-1" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>This was an experiment. The values of the predictors (<strong>Fingers</strong> and
<strong>Objects</strong>) were decided by the experimenters, so they are uncorrelated
causes of the outcome (<strong>Time</strong>).</p>
<p><strong>Specific Hypotheses:</strong></p>
<ol style="list-style-type: decimal">
<li><p>Handling wet objects will take longer than handling dry objects</p></li>
<li><p>Handling objects with wet fingers will take longer than with dry fingers</p></li>
<li><p>Handling wet objects will be faster if done with wet/wrinkled fingers than with dry fingers</p></li>
<li><p>Handling time for dry objects will NOT be affected by whether the fingers are wet or dry</p></li>
</ol>
</div>
<div id="statistical-model-1" class="section level2 unnumbered hasAnchor">
<h2>Statistical Model<a href="an-introduction-to-lavaan-how-do-wet-fingers-wrinkle-1.html#statistical-model-1" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>The hypothesis is not simply that wet fingers and wet objects will
result in slower handling time, it is that wet fingers will reduce the
slowing effect of handling wet objects specifically. This implies an
interaction between <strong>Fingers</strong> and <strong>Objects</strong>.</p>
</div>
<div id="preparing-the-data-1" class="section level2 unnumbered hasAnchor">
<h2>Preparing the Data<a href="an-introduction-to-lavaan-how-do-wet-fingers-wrinkle-1.html#preparing-the-data-1" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>First we’ll create numerical dummy variables for having wet (wrinkled)
fingers and wet objects.</p>
<div class="sourceCode" id="cb42"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb42-1"><a href="an-introduction-to-lavaan-how-do-wet-fingers-wrinkle-1.html#cb42-1" tabindex="-1"></a>wrinkle <span class="ot">&lt;-</span> <span class="fu">dummy_cols</span>(wrinkle, <span class="at">select_columns =</span> <span class="st">&quot;Fingers&quot;</span>)</span>
<span id="cb42-2"><a href="an-introduction-to-lavaan-how-do-wet-fingers-wrinkle-1.html#cb42-2" tabindex="-1"></a>wrinkle <span class="ot">&lt;-</span> <span class="fu">dummy_cols</span>(wrinkle, <span class="at">select_columns =</span> <span class="st">&quot;Objects&quot;</span>)</span></code></pre></div>
<p>We now have two new dummy variables: <strong>Fingers_wrinkled</strong> and
<strong>Objects_wet</strong></p>
<div class="sourceCode" id="cb43"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb43-1"><a href="an-introduction-to-lavaan-how-do-wet-fingers-wrinkle-1.html#cb43-1" tabindex="-1"></a><span class="fu">head</span>(wrinkle)</span></code></pre></div>
<pre><code>##   rownames Participant Time        Condition Fingers Objects WrinkledThenNon
## 1        1          p1  106 non-wrinkled/dry     non     dry               1
## 2        2          p2  113 non-wrinkled/dry     non     dry               2
## 3        3          p3   94 non-wrinkled/dry     non     dry               1
## 4        4          p4   96 non-wrinkled/dry     non     dry               2
## 5        5          p5   93 non-wrinkled/dry     non     dry               1
## 6        6          p6  123 non-wrinkled/dry     non     dry               2
##   DryThenWet Fingers_non Fingers_wrinkled Objects_dry Objects_wet
## 1          1           1                0           1           0
## 2          1           1                0           1           0
## 3          1           1                0           1           0
## 4          1           1                0           1           0
## 5          1           1                0           1           0
## 6          1           1                0           1           0</code></pre>
<p>And then we create an interaction variable for <strong>Fingers</strong> and
<strong>Objects</strong>.</p>
<div class="sourceCode" id="cb45"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb45-1"><a href="an-introduction-to-lavaan-how-do-wet-fingers-wrinkle-1.html#cb45-1" tabindex="-1"></a>wrinkle<span class="sc">$</span>Interaction <span class="ot">&lt;-</span> wrinkle<span class="sc">$</span>Fingers_wrinkled<span class="sc">*</span>wrinkle<span class="sc">$</span>Objects_wet</span></code></pre></div>
<p>Finally, lets’s re-organise the data so that it can be used with
<code>ggplot2</code>, so we can visualise the data. We need to convert the
<strong>Participant</strong> variable to a numeric variable so that we can sort it
correctly. We’ll use the <code>str_replace()</code> function from the <code>stringr</code>
library to remove the “p” from the <strong>Participant</strong> variable, and then
convert it to a numeric variable using <code>as.numeric()</code>. We’ll then use
<code>relocate()</code> from <code>dplyr</code> to move the <strong>id</strong> variable to the second
column. Finally, we’ll use <code>arrange()</code> also from <code>dplyr</code> to sort the
dataframe by the <strong>id</strong> variable. We’ll save the sorted dataframe as
<strong>wrinkle2</strong>.</p>
<div class="sourceCode" id="cb46"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb46-1"><a href="an-introduction-to-lavaan-how-do-wet-fingers-wrinkle-1.html#cb46-1" tabindex="-1"></a>wrinkle2  <span class="ot">&lt;-</span> wrinkle <span class="sc">%&gt;%</span> </span>
<span id="cb46-2"><a href="an-introduction-to-lavaan-how-do-wet-fingers-wrinkle-1.html#cb46-2" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">id =</span> <span class="fu">as.numeric</span>(<span class="fu">str_replace</span>(Participant, <span class="st">&quot;p&quot;</span>, <span class="st">&quot;&quot;</span>))) <span class="sc">%&gt;%</span></span>
<span id="cb46-3"><a href="an-introduction-to-lavaan-how-do-wet-fingers-wrinkle-1.html#cb46-3" tabindex="-1"></a>  <span class="fu">relocate</span>(id, <span class="at">.after =</span> Participant) <span class="sc">%&gt;%</span></span>
<span id="cb46-4"><a href="an-introduction-to-lavaan-how-do-wet-fingers-wrinkle-1.html#cb46-4" tabindex="-1"></a>  <span class="fu">arrange</span>(id)</span></code></pre></div>
</div>
<div id="visualing-the-data-1" class="section level2 unnumbered hasAnchor">
<h2>Visualing the Data<a href="an-introduction-to-lavaan-how-do-wet-fingers-wrinkle-1.html#visualing-the-data-1" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>Great, now we have a dataset that we can use with <code>ggplot2</code>. We can use
either <strong>wrinkle</strong> or <strong>wrinkle2</strong> to analyse the data with <code>lm()</code> and
<code>lavaan</code>.</p>
<p>Let’s see the completion time for each condition as a boxplot.</p>
<div class="sourceCode" id="cb47"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb47-1"><a href="an-introduction-to-lavaan-how-do-wet-fingers-wrinkle-1.html#cb47-1" tabindex="-1"></a>wrinkle2 <span class="sc">%&gt;%</span></span>
<span id="cb47-2"><a href="an-introduction-to-lavaan-how-do-wet-fingers-wrinkle-1.html#cb47-2" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> Fingers, <span class="at">y =</span> Time)) <span class="sc">+</span></span>
<span id="cb47-3"><a href="an-introduction-to-lavaan-how-do-wet-fingers-wrinkle-1.html#cb47-3" tabindex="-1"></a>  <span class="fu">geom_boxplot</span>() <span class="sc">+</span></span>
<span id="cb47-4"><a href="an-introduction-to-lavaan-how-do-wet-fingers-wrinkle-1.html#cb47-4" tabindex="-1"></a>  <span class="fu">facet_wrap</span>( <span class="sc">~</span> Objects)</span></code></pre></div>
<p><img src="01-S01-ANS_files/figure-html/unnamed-chunk-14-1.png" width="672" /></p>
<p>We have four boxplots, one for each condition. The thick black
horizontal line in the middle of each box is the median time to complete
the task. The upper and lower edges of the box are the 75th and 25th
percentiles of completion times for each condition. The “whiskers”
extend to the most extreme completion times, that represent the 2.5% and
97.5% percentiles of the data. The dots are “outliers” - completion
times that are so extreme that they are outside of the whiskers, which
represent 95% of the data. It’s clear that handling wet objects with dry
(“non” wrinkled) fingers has the highest median handling time.</p>
<p>Let’s now take a look at a line graph of the interaction. First, we
compute a summary statistic (the mean) for each condition.</p>
<div class="sourceCode" id="cb48"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb48-1"><a href="an-introduction-to-lavaan-how-do-wet-fingers-wrinkle-1.html#cb48-1" tabindex="-1"></a>wrinkle2_summary  <span class="ot">&lt;-</span> wrinkle2 <span class="sc">%&gt;%</span></span>
<span id="cb48-2"><a href="an-introduction-to-lavaan-how-do-wet-fingers-wrinkle-1.html#cb48-2" tabindex="-1"></a>  <span class="fu">group_by</span>(Fingers, Objects) <span class="sc">%&gt;%</span></span>
<span id="cb48-3"><a href="an-introduction-to-lavaan-how-do-wet-fingers-wrinkle-1.html#cb48-3" tabindex="-1"></a>  <span class="fu">summarise</span>(<span class="at">Mean_time =</span> <span class="fu">mean</span>(Time))</span></code></pre></div>
<pre><code>## `summarise()` has grouped output by &#39;Fingers&#39;. You can override using the
## `.groups` argument.</code></pre>
<p>Then, we plot the above statistics.</p>
<div class="sourceCode" id="cb50"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb50-1"><a href="an-introduction-to-lavaan-how-do-wet-fingers-wrinkle-1.html#cb50-1" tabindex="-1"></a>wrinkle2_summary <span class="sc">%&gt;%</span></span>
<span id="cb50-2"><a href="an-introduction-to-lavaan-how-do-wet-fingers-wrinkle-1.html#cb50-2" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> Fingers, <span class="at">y =</span> Mean_time, <span class="at">color =</span> Objects)) <span class="sc">+</span></span>
<span id="cb50-3"><a href="an-introduction-to-lavaan-how-do-wet-fingers-wrinkle-1.html#cb50-3" tabindex="-1"></a>  <span class="fu">geom_line</span>(<span class="fu">aes</span>(<span class="at">group =</span> Objects)) <span class="sc">+</span></span>
<span id="cb50-4"><a href="an-introduction-to-lavaan-how-do-wet-fingers-wrinkle-1.html#cb50-4" tabindex="-1"></a>  <span class="fu">geom_point</span>()</span></code></pre></div>
<p><img src="01-S01-ANS_files/figure-html/unnamed-chunk-16-1.png" width="672" /></p>
<p>The dots show the mean completion time for each condition. The lines
connect the dots for the same object type. The lines are not parallel,
which suggests that we have an interaction between Fingers and Objects.
However, this graph does not show us the uncertainty in the mean
completion times. (The graph is also misleading because the y-axis does
not begin at zero, which makes the differences across contitions look
larger than they are.)</p>
<p>To fully assess our hypotheses, we need to fit statistical models of the
mean differences, which take into account the uncertainty in the mean
completion times, by computing standard errors (SEs) for the
differences.</p>
</div>
<div id="the-lavaan-package-2" class="section level2 unnumbered hasAnchor">
<h2>The <code>lavaan</code> Package<a href="an-introduction-to-lavaan-how-do-wet-fingers-wrinkle-1.html#the-lavaan-package-2" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>With <code>lavaan</code>, we define the statistical model as an object and we name it <strong>model</strong>. The object specification is enclosed in single quotes. As you can see below, the model structure is similar to that of <code>lm()</code>.</p>
<div class="sourceCode" id="cb51"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb51-1"><a href="an-introduction-to-lavaan-how-do-wet-fingers-wrinkle-1.html#cb51-1" tabindex="-1"></a>model <span class="ot">&lt;-</span> <span class="st">&#39;Time ~ Fingers_wrinkled + Objects_wet + Interaction&#39;</span></span></code></pre></div>
<p>To then fit the model to the data, we use the <code>sem()</code> function.</p>
<div class="sourceCode" id="cb52"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb52-1"><a href="an-introduction-to-lavaan-how-do-wet-fingers-wrinkle-1.html#cb52-1" tabindex="-1"></a>fit_lav <span class="ot">&lt;-</span> <span class="fu">sem</span>(model, <span class="at">data=</span>wrinkle2, <span class="at">meanstructure =</span> <span class="cn">TRUE</span>)</span></code></pre></div>
<p>One difference is that <code>lavaan</code> does not include intercepts in the model by default, so we have to ask for them by including the option <code>meanstructure = TRUE</code>.</p>
<p>Let’s take a look at the output.</p>
<div class="sourceCode" id="cb53"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb53-1"><a href="an-introduction-to-lavaan-how-do-wet-fingers-wrinkle-1.html#cb53-1" tabindex="-1"></a><span class="fu">summary</span>(fit_lav)</span></code></pre></div>
<pre><code>## lavaan 0.6-18 ended normally after 1 iteration
## 
##   Estimator                                         ML
##   Optimization method                           NLMINB
##   Number of model parameters                         5
## 
##   Number of observations                            80
## 
## Model Test User Model:
##                                                       
##   Test statistic                                 0.000
##   Degrees of freedom                                 0
## 
## Parameter Estimates:
## 
##   Standard errors                             Standard
##   Information                                 Expected
##   Information saturated (h1) model          Structured
## 
## Regressions:
##                    Estimate  Std.Err  z-value  P(&gt;|z|)
##   Time ~                                              
##     Fingers_wrnkld    0.850    6.257    0.136    0.892
##     Objects_wet      24.600    6.257    3.932    0.000
##     Interaction     -15.900    8.849   -1.797    0.072
## 
## Intercepts:
##                    Estimate  Std.Err  z-value  P(&gt;|z|)
##    .Time             93.300    4.424   21.088    0.000
## 
## Variances:
##                    Estimate  Std.Err  z-value  P(&gt;|z|)
##    .Time            391.489   61.900    6.325    0.000</code></pre>
<p>As you can see, there is a lot more output than from <code>lm()</code>! For now, we will focus on the part starting at <code>regressions</code>.</p>
</div>
<div id="task-1-1" class="section level2 unnumbered hasAnchor">
<h2>TASK 1<a href="an-introduction-to-lavaan-how-do-wet-fingers-wrinkle-1.html#task-1-1" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>Fit a linear model using <code>lm()</code> to evaluate the effect of the predictors
<strong>Fingers</strong> and <strong>Objects</strong>, and their interaction, on outcome <strong>Time</strong>.</p>
<p>Are the specific hypotheses supported by the data?</p>
<p>Let’s fit the model.</p>
<div class="sourceCode" id="cb55"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb55-1"><a href="an-introduction-to-lavaan-how-do-wet-fingers-wrinkle-1.html#cb55-1" tabindex="-1"></a>fit_lm <span class="ot">&lt;-</span> <span class="fu">lm</span>(Time <span class="sc">~</span> Fingers_wrinkled <span class="sc">+</span> Objects_wet <span class="sc">+</span> Interaction, <span class="at">data =</span> wrinkle2)</span>
<span id="cb55-2"><a href="an-introduction-to-lavaan-how-do-wet-fingers-wrinkle-1.html#cb55-2" tabindex="-1"></a></span>
<span id="cb55-3"><a href="an-introduction-to-lavaan-how-do-wet-fingers-wrinkle-1.html#cb55-3" tabindex="-1"></a><span class="fu">summary</span>(fit_lm)</span></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = Time ~ Fingers_wrinkled + Objects_wet + Interaction, 
##     data = wrinkle2)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -29.900 -15.113  -2.025  11.925  80.100 
## 
## Coefficients:
##                  Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)        93.300      4.539  20.554  &lt; 2e-16 ***
## Fingers_wrinkled    0.850      6.420   0.132  0.89501    
## Objects_wet        24.600      6.420   3.832  0.00026 ***
## Interaction       -15.900      9.079  -1.751  0.08391 .  
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 20.3 on 76 degrees of freedom
## Multiple R-squared:  0.1997, Adjusted R-squared:  0.1681 
## F-statistic: 6.323 on 3 and 76 DF,  p-value: 0.0006927</code></pre>
<p>If we explore the residuals, we can note that none of the plots reveals a major problem.</p>
<div class="sourceCode" id="cb57"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb57-1"><a href="an-introduction-to-lavaan-how-do-wet-fingers-wrinkle-1.html#cb57-1" tabindex="-1"></a><span class="fu">plot</span>(fit_lm)</span></code></pre></div>
<p><img src="01-S01-ANS_files/figure-html/unnamed-chunk-21-1.png" width="672" /><img src="01-S01-ANS_files/figure-html/unnamed-chunk-21-2.png" width="672" /></p>
<pre><code>## hat values (leverages) are all = 0.05
##  and there are no factor predictors; no plot no. 5</code></pre>
<p><img src="01-S01-ANS_files/figure-html/unnamed-chunk-21-3.png" width="672" /><img src="01-S01-ANS_files/figure-html/unnamed-chunk-21-4.png" width="672" /></p>
<p>Substantive interpretation of the coefficients:</p>
<table>
<colgroup>
<col width="22%" />
<col width="13%" />
<col width="63%" />
</colgroup>
<tbody>
<tr class="odd">
<td><strong>Coefficient</strong></td>
<td><strong>Value</strong></td>
<td><strong>Interpretation</strong></td>
</tr>
<tr class="even">
<td>Intercept</td>
<td>93.300</td>
<td>Mean time to handle dry objects with dry hands</td>
</tr>
<tr class="odd">
<td>Fingers_wrinkled</td>
<td>0.850</td>
<td>Additional time to handle dry objects with wet hands</td>
</tr>
<tr class="even">
<td>Objects_wet</td>
<td>24.600</td>
<td>Additional time to handle wet objects with dry hands Interaction</td>
</tr>
<tr class="odd">
<td>Interaction</td>
<td>15.900</td>
<td>Difference from above when handling wet objects with wet hands</td>
</tr>
</tbody>
</table>
<p>The pattern of coefficients supports the hypotheses: Handling wet objects with dry hands takes on average <span class="math inline">\(24.6\)</span> seconds longer than handling dry objects with dry hands, but if the hands are wet when handling the wet objects, it takes <span class="math inline">\(15.9\)</span> seconds less than this: It takes <span class="math inline">\(24.6\)</span> seconds longer to handle wet objects with dry hands than dry objects with dry hands. It takes <span class="math inline">\(24.6 - 15.9 = 8.7\)</span> seconds longer to handle wet objects with wet hands than it takes to handle dry objects with dry hands.</p>
<p>However, the SE for the Interaction is <span class="math inline">\(9.079\)</span>, so the <span class="math inline">\(95%\)</span> confidence interval is:</p>
<p>Lower Bound <span class="math inline">\(CI_{95\%} = -15.9 - (2 \times 9.079) = -34.058\)</span></p>
<p>Upper bound <span class="math inline">\(CI_{95\%} = -15.9 + (2 \times 9.079) = 2.258\)</span></p>
<p>This shows us the plausible range of values for the interaction in the population. This range includes zero - the effect could plausibly be zero in the population. The interaction effect is therefore non-significant. The key hypothesis of an interaction between Fingers and Wrinkled is <strong>not</strong> supported by the results of this model.</p>
</div>
<div id="task-2-1" class="section level2 unnumbered hasAnchor">
<h2>TASK 2<a href="an-introduction-to-lavaan-how-do-wet-fingers-wrinkle-1.html#task-2-1" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>What are the differences between the <code>lm()</code> and <code>lavaan</code> results? Why might these differences exist?</p>
<p>The estimates for the b coefficients are exactly the same. The standard errors are all a bit smaller. This is because this model was not estimated using OLS. By default, <code>lavaan</code> uses “maximum likelihood” (ML) estimation. ML uses an iterative algorithm that selects the model parameters that were “most likely” to have resulted in the observed data. ML makes an additional assumption that OLS does not - it assumes the residuals are normally distributed. If the residuals are plausibly from a normal distribution, the ML estimator is more “efficient”, especially in small samples. “Efficient” means that it has smaller standard errors. Because the SEs are slightly smaller, the p-values are also slightly lower. However, the Interaction effect is still non-significant (<span class="math inline">\(p=0.072\)</span>).</p>
<p><code>lavaan</code> hasn’t given us <span class="math inline">\(R^2\)</span>, but we can work it out for ourselves:</p>
<p><span class="math inline">\(R^2 = \frac{(var_0 - var_1)}{var_0}\)</span>, where <span class="math inline">\(var_0\)</span> is the variance of the outcome variable, and <span class="math inline">\(var1\)</span> is the variance of the residuals after fitting the model.</p>
<p>From the output, we find that <span class="math inline">\(var_1\)</span> (residual variance of Time) is <span class="math inline">\(391.489\)</span>. We can then obtain <span class="math inline">\(var_0\)</span> by:</p>
<div class="sourceCode" id="cb59"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb59-1"><a href="an-introduction-to-lavaan-how-do-wet-fingers-wrinkle-1.html#cb59-1" tabindex="-1"></a>var_0 <span class="ot">&lt;-</span> <span class="fu">var</span>(wrinkle2<span class="sc">$</span>Time)</span></code></pre></div>
<p>Therefore, <span class="math inline">\(R^2 = \frac{(495.3899 - 391.489)}{495.3899} = 0.21\)</span></p>
<p>This is slightly higher than the value computed by <code>lm()</code>, because <code>lavaan</code> uses the sample size <span class="math inline">\(N\)</span> to compute variances, rather than <span class="math inline">\(N-1\)</span> as <code>lm()</code> does.</p>
<p><em>TIP: To get the same <span class="math inline">\(R^2\)</span> as <code>lm()</code>, include the option: <code>likelihood = "wishart"</code> in the model estimation command.</em></p>
<p>An assumption of both <code>lm()</code> and <code>lavaan</code> models above is that the observations are independent. Let’s see:</p>
<div class="sourceCode" id="cb60"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb60-1"><a href="an-introduction-to-lavaan-how-do-wet-fingers-wrinkle-1.html#cb60-1" tabindex="-1"></a><span class="fu">glimpse</span>(wrinkle2)</span></code></pre></div>
<pre><code>## Rows: 80
## Columns: 14
## $ rownames         &lt;int&gt; 1, 21, 41, 61, 2, 22, 42, 62, 3, 23, 43, 63, 4, 24, 4…
## $ Participant      &lt;chr&gt; &quot;p1&quot;, &quot;p1&quot;, &quot;p1&quot;, &quot;p1&quot;, &quot;p2&quot;, &quot;p2&quot;, &quot;p2&quot;, &quot;p2&quot;, &quot;p3&quot;,…
## $ id               &lt;dbl&gt; 1, 1, 1, 1, 2, 2, 2, 2, 3, 3, 3, 3, 4, 4, 4, 4, 5, 5,…
## $ Time             &lt;int&gt; 106, 139, 107, 118, 113, 138, 97, 106, 94, 136, 117, …
## $ Condition        &lt;chr&gt; &quot;non-wrinkled/dry&quot;, &quot;non-wrinkled/wet&quot;, &quot;wrinkled/dry…
## $ Fingers          &lt;chr&gt; &quot;non&quot;, &quot;non&quot;, &quot;wrinkled&quot;, &quot;wrinkled&quot;, &quot;non&quot;, &quot;non&quot;, &quot;…
## $ Objects          &lt;chr&gt; &quot;dry&quot;, &quot;wet&quot;, &quot;dry&quot;, &quot;wet&quot;, &quot;dry&quot;, &quot;wet&quot;, &quot;dry&quot;, &quot;wet…
## $ WrinkledThenNon  &lt;int&gt; 1, 1, 1, 1, 2, 2, 2, 2, 1, 1, 1, 1, 2, 2, 2, 2, 1, 1,…
## $ DryThenWet       &lt;int&gt; 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,…
## $ Fingers_non      &lt;int&gt; 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1,…
## $ Fingers_wrinkled &lt;int&gt; 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0,…
## $ Objects_dry      &lt;int&gt; 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0,…
## $ Objects_wet      &lt;int&gt; 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1,…
## $ Interaction      &lt;int&gt; 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0,…</code></pre>
<p>There are only 20 participants, but there are 80 rows of data: Each participant did the task four times, and has four rows of data. These observations are therefore not independent, they are clustered within participants. This violates the independence assumption of the residuals in these simple linear models.</p>
<p>What can we do?</p>
<p>With <code>lavaan</code>, we can relax this assumption by allowing for the clustering when computing the model SEs (the independence assumption only affects the SEs, not the b-values themselves.</p>
<div class="sourceCode" id="cb62"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb62-1"><a href="an-introduction-to-lavaan-how-do-wet-fingers-wrinkle-1.html#cb62-1" tabindex="-1"></a>fit_lav_clus <span class="ot">&lt;-</span> <span class="fu">sem</span>(model, <span class="at">data =</span> wrinkle2, <span class="at">meanstructure =</span> <span class="cn">TRUE</span>, </span>
<span id="cb62-2"><a href="an-introduction-to-lavaan-how-do-wet-fingers-wrinkle-1.html#cb62-2" tabindex="-1"></a>                    <span class="at">cluster =</span> <span class="st">&quot;Participant&quot;</span>)</span></code></pre></div>
<p>The <code>cluster</code> command tells <code>lavaan</code> that the observations (rows) are clustered within values of <strong>Participant</strong>. It then computes “robust” SEs, taking this non-independence into account.</p>
<div class="sourceCode" id="cb63"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb63-1"><a href="an-introduction-to-lavaan-how-do-wet-fingers-wrinkle-1.html#cb63-1" tabindex="-1"></a><span class="fu">summary</span>(fit_lav_clus)</span></code></pre></div>
<pre><code>## lavaan 0.6-18 ended normally after 1 iteration
## 
##   Estimator                                         ML
##   Optimization method                           NLMINB
##   Number of model parameters                         5
## 
##   Number of observations                            80
##   Number of clusters [Participant]                  20
## 
## Model Test User Model:
##                                               Standard      Scaled
##   Test Statistic                                 0.000       0.000
##   Degrees of freedom                                 0           0
## 
## Parameter Estimates:
## 
##   Standard errors                        Robust.cluster
##   Information                                  Observed
##   Observed information based on                 Hessian
## 
## Regressions:
##                    Estimate  Std.Err  z-value  P(&gt;|z|)
##   Time ~                                              
##     Fingers_wrnkld    0.850    2.573    0.330    0.741
##     Objects_wet      24.600    3.833    6.418    0.000
##     Interaction     -15.900    2.365   -6.722    0.000
## 
## Intercepts:
##                    Estimate  Std.Err  z-value  P(&gt;|z|)
##    .Time             93.300    3.191   29.243    0.000
## 
## Variances:
##                    Estimate  Std.Err  z-value  P(&gt;|z|)
##    .Time            391.489  139.008    2.816    0.005</code></pre>
</div>
<div id="task-3-1" class="section level2 unnumbered hasAnchor">
<h2>Task 3<a href="an-introduction-to-lavaan-how-do-wet-fingers-wrinkle-1.html#task-3-1" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>How have the results changed after relaxing the independence assumption?
Would your answer to the research question change?</p>
<p>YES! The values of the b-coefficients have not changed, but the SEs are now corrected for clustering within participants and are now very much smaller than before. (This is unusual - for much social data we would expect the SEs to be larger after correction for clustering, but this was a well-designed experiment where the clustering was “explained” by the design.)</p>
<p>The SE for the Interaction is <span class="math inline">\(2.365\)</span>, so the <span class="math inline">\(95%\)</span> confidence interval is:</p>
<p>Lower Bound <span class="math inline">\(CI_{95%} = -15.9 - (2 \times 2.365) = -20.63\)</span></p>
<p>Upper bound <span class="math inline">\(CI_{95%} = -15.9 + (2 \times 2.365) = -11.17\)</span></p>
<p>The <span class="math inline">\(95%\)</span> confidence interval does NOT include zero! The plausible population values for the improvement in handling time for wet objects when the hands are wet/wrinkled compared to dry is now between <span class="math inline">\(11.17\)</span> and <span class="math inline">\(20.63\)</span> seconds faster.</p>
<p><strong>In summary, <code>lavaan</code> can do everything that <code>lm()</code> can do, and much, much more as we will see. But be aware that there are differences, for example in the default methods for model estimation (ML vs OLS).</strong></p>

</div>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="an-introduction-to-lavaan-how-do-wet-fingers-wrinkle.html" class="navigation navigation-prev navigation-unique" aria-label="Previous page"><i class="fa fa-angle-left"></i></a>

    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": null,
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": null,
"text": null
},
"history": {
"link": null,
"text": null
},
"view": {
"link": null,
"text": null
},
"download": null,
"search": {
"engine": "fuse",
"options": null
},
"toc": {
"collapse": "section"
}
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.9/latest.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
